window.POWERDUCK_ITEMS = [
  {
    slug: "that-month-i-lost-to-lonesome-dove",
    title: "Lonesome Dove",
    category: "Book",
    description: "Larry McMurtry's Pulitzer Prize-winning novel transformed the dusty Western genre into something profound and heartbreaking. Following aging Texas Rangers Gus McCrae and Woodrow Call as they drive cattle from the Rio Grande to Montana, this massive story captures the end of the frontier with unflinching honesty. It's a meditation on friendship, mortality, and the brutal poetry of the American West that spawned one of television's greatest miniseries.",
    image: "images/generated/that-month-i-lost-to-lonesome-dove-898c2299.webp",
    imageAspect: "landscape",
    imageFit: "contain",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=that-month-i-lost-to-lonesome-dove",
    detailLabel: "More from me"
  },
  {
    title: "Ascii Aquarium",
    category: "",
    description: "Wanna see an ascii aquarium? Inspired by that one you've probably seen banging around on the internet. Click and it'll open :)",
    image: "images/fih.png",
    url: "https://powerduck.neocities.org/aquarium"
  },
  {
    title: "Gear - Demon core flail",
    category: "",
    description: "The Demon Core Flail is a simple improvement on the classic medieval design. Instead of a steel ball, the striking head is a genuine Demon Core mounted on a short chain and walnut handle. Elegant, compact, and capable of delivering both blunt force trauma and a highly persuasive burst of radiation.\n\nIn theory the physics are straightforward. Swing the core, build momentum, and introduce it to whatever problem is in front of you. In practice the user may also experience a brief but educational lesson in nuclear criticality.",
    image: "images/dc.png"
  },
  {
    title: "Ventoy",
    category: "Software",
    description: "Making a bootable USB normally kind of sucks. The moment you do it, that USB stops being a normal drive and becomes that one operating system. Want something different later? Back to the Rufus dick drag of formatting the drive and burning another ISO.\n\nVentoy fixes that!! Install it once and just drop ISO files onto the USB like normal files. When you boot the computer it lets you pick whichever one you want, and the drive still works like a normal USB for everything else. One stick now can install whatever OS you like AND work as a regular USB drive. Black. Magic.",
    image: "images/generated/software-ventoy-144a1962.webp",
    url: "https://www.ventoy.net/en/index.html",
    slug: "software-ventoy",
    imageAspect: "landscape",
    imageFit: "contain",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=software-ventoy",
    detailLabel: "More from me"
  },
  {
    title: "Bambulabs A1",
    category: "Gear",
    description: "If you want to get into 3D printing but spend more time actually printing than working on your printer it's hard to go past this little beast. It's probably the current best bang for your buck on the market if you value a balance of print speed, quality and affordability. I've had mine for long enough at this point to know it's a fantastic product. I strongly recommend it!",
    image: "images/generated/gear-bambulabs-a1-02d19414.jpg",
    url: "https://bambulab.com/en-us/a1-mini",
    buttonLabel: "Go and See",
    slug: "gear-bambulabs-a1",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-bambulabs-a1",
    detailLabel: "More from me"
  },
  {
    title: "Kobo Clara BW",
    category: "Gear",
    description: "Amazon Kindle? Nah. Kobo Clara! Install KoReader on it for all the untethered goodness you could want. I’ve installed a file manage plugin so I can send ePub format books straight to it from my phone over Wifi. Custom screensavers and one touch immediate return to your last reading position. Oh and if you have multiple eReaders you can sync them with KoReader so they all resume from the same point! Keen for my Xteink X4 to turn up for more convenient reading on the go!",
    image: "images/generated/gear-kobo-clara-bw-265f2eb4.png",
    url: "https://us.kobobooks.com/products/kobo-clara-bw?utm_source=Kobo&utm_medium=TopNav&utm_campaign=ClaraBW",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=gear-kobo-clara-bw",
    detailLabel: "More from me",
    slug: "gear-kobo-clara-bw",
    imageAspect: "landscape",
    imageFit: "contain"
  },
  {
    title: "DIY Eptaora Flip Digit Clock",
    category: "Gear",
    description: "Tell me you don't like seven segmented digital displays. This thing is awesome. It's blending admirable, but simple mechanics and great function. It's an art piece as much as it's a clock.",
    image: "images/generated/gear-diy-eptaora-flip-digit-clock-cde4aef2.webp",
    url: "https://www.kickstarter.com/projects/mectolab/eptaora-an-electromechanical-clock",
    slug: "gear-diy-eptaora-flip-digit-clock",
    imageAspect: "landscape",
    imageFit: "contain",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=gear-diy-eptaora-flip-digit-clock",
    detailLabel: "More from me"
  },
  {
    title: "Dungeon Crawler Carl",
    category: "Book",
    description: "What a banger. Simple and fun. Earth is destroyed by aliens and the surviving humans are forced into a brutal intergalactic reality TV show.The planet becomes a massive dungeon filled with traps, monsters, and absurd challenges that contestants must survive while the galaxy watches for entertainment. Carl, a former Coast Guard vet, enters the dungeon with his ex-girlfriend’s show cat, Princess Donut. Together they try to survive each level, dealing with bizarre enemies, magical items, and deadly game mechanics while millions of alien viewers treat their suffering like a spectacle.",
    image: "images/generated/book-dungeon-crawler-carl-b3fe6ad3.png",
    url: "https://www.goodreads.com/book/show/56791389-dungeon-crawler-carl",
    slug: "book-dungeon-crawler-carl",
    imageAspect: "landscape",
    imageFit: "cover",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=book-dungeon-crawler-carl",
    detailLabel: "More from me"
  },
  {
    title: "Lodge Cast Iron",
    category: "Gear",
    description: "Such a classic. Buy it for life. Doesn't matter what you choose from Lodges line, it's going to outlast you. Cast iron does need a little extra love compared to the nonstick stuff but just keep using it and wiping it out with a paper towel. A good cast iron pan retains heat, works on any hob and is admirably non stick when you get it up to temp. Learn how to use it and you'll never look back.",
    image: "images/generated/gear-lodge-cast-iron-cb501213.png",
    url: "https://www.lodgecastiron.com/",
    slug: "gear-lodge-cast-iron",
    imageAspect: "landscape",
    imageFit: "cover",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=gear-lodge-cast-iron",
    detailLabel: "More from me"
  },
  {
    title: "Takopi's Original Sin",
    category: "Anime",
    description: "What starts as an innocent-looking story about a friendly alien octopus quickly becomes one of the most psychologically devastating anime experiences in recent memory. Takopi's Original Sin uses its deceptively cheerful art style as a Trojan horse for themes so dark and heavy that you'll question how it ever made it to air. This isn't your typical feel good alien friendship stor... It's a masterclass in emotional manipulation that will leave you staring at the ceiling at 3 AM.",
    image: "images/generated/anime-takopis-original-sin-a4288371.png",
    url: "https://www.imdb.com/title/tt36988358/",
    slug: "anime-takopis-original-sin",
    imageAspect: "landscape",
    imageFit: "contain",
    buttonLabel: "Go and See",
    detailUrl: "post.html?slug=anime-takopis-original-sin",
    detailLabel: "More from me"
  },
  {
    title: "YouTube Video - THE INTERNET IS BACK",
    category: "",
    description: "I watched this video by onionboots and was immediately inspired to carve out my own little bit of internet. I have been so happy working on this website project over the last week. I am really pleased with how it's turning out. Thank you onionboots! I absolutely would not have been here without you. Onio.club is an inspiration!",
    image: "images/onionboots.png",
    url: "https://www.youtube.com/watch?v=tkUgOT22F5s&t=520s"
  },
  {
    title: "Video game - Duck Invaders",
    category: "",
    description: "I made a game for this website, you can play it by clicking the Duck Invaders button the left side of the screen. It's set up for keyboard/mouse/touch controls so It should work on your PC, phone or tablet. There is a global leaderboard that will show the top 15 scores. Can you get the top score?",
    image: "images/duckinvaders.png",
    url: "",
    buttonLabel: "",
    detailUrl: "game-duck-invaders.html",
    detailLabel: "More from Me"
  },
  {
    title: "Video game - Caves of Qud",
    category: "",
    description: "Caves of Qud looks simple, but that minimalism is what lets it go completely off the rails. You can give a door sentience, swap bodies with it, and then play the rest of the game as the door. You can cut a goat man’s face off, throw it at his friend, eat it, or wear it as a mask and Qud just quietly accepts it. The graphics aren’t a limitation, they’re what make all this ridiculous depth possible. Play this game.",
    image: "images/IMG_1598.jpg",
    url: "https://store.steampowered.com/app/333640/Caves_of_Qud/",
    buttonLabel: "Go and See"
  },
  {
    title: "Lansky Knife Sharpening System",
    category: "Gear",
    description: "Honestly, your knives are probably blunt. More honestly, you probably can't sharpen them properly. The Lansky takes a lot of the guess work out of sharpening your knives by guiding the stones across the blade at fixed angles. Even a rookie can get a respectable edge back with one of these kits in no time! If you don't have the time to put into learning the skills to use a stone, use a Lansky. Please never use a pull through sharpener :'(",
    image: "images/generated/gear-lansky-knife-sharpening-system-b24c3fe7.png",
    url: "https://lanskyuk.shop/",
    buttonLabel: "Go and See",
    slug: "gear-lansky-knife-sharpening-system",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-lansky-knife-sharpening-system",
    detailLabel: "More from me"
  },
  {
    title: "Jean Paul Gaultier Le Male Elixir",
    category: "Gear",
    description: "I don't know if I'd call this my signature fragrance but I do go through quite a lot of it! I love it, but be careful with this stuff. People will smell you before they see you coming! (And they'll usually love it too)",
    image: "images/generated/gear-jean-paul-gaultier-le-male-elixir-b42e88ee.jpeg",
    url: "https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-81642.html",
    buttonLabel: "Go and See",
    slug: "gear-jean-paul-gaultier-le-male-elixir",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-jean-paul-gaultier-le-male-elixir",
    detailLabel: "More from me"
  },
  {
    title: "Lonesome Dove",
    category: "Book",
    description: "I've picked this up with the intention of getting back into reading more. It's an absolute tome of a novel at around a thousand pages but I'm enjoying it so far. I might have to come back and leave a review when I'm done... eventually...",
    image: "images/generated/book-lonesome-dove-92d437e2.jpeg",
    url: "https://www.goodreads.com/book/show/256008.Lonesome_Dove",
    buttonLabel: "Go and See",
    slug: "book-lonesome-dove",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=book-lonesome-dove",
    detailLabel: "More from me"
  },
  {
    title: "Olight i3e EOS AAA flashlight",
    category: "Gear",
    description: "I love USB-C everything too, but you know what sucks? When the internal battery actually dies and your device is left obsolete. Or having to charge a light when you don't have power... Change out the internal AAA and you're ready to go in no time. Don't ever forget, swappable batteries still have their place!",
    image: "images/generated/gear-olight-i3e-eos-aaa-flashlight-037effdc.png",
    url: "https://www.olight.com/store/i3e-eos",
    buttonLabel: "Go and See",
    slug: "gear-olight-i3e-eos-aaa-flashlight",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-olight-i3e-eos-aaa-flashlight",
    detailLabel: "More from me"
  },
  {
    title: "FiiO JadeAudio JT7 Open-Back Planar Headphones",
    category: "Gear",
    description: "These are planar headphones. They're ridiculously comfortable and sound incredible. Very hard to beat in terms of bang for your buck. The build quality is also fantastic. They don't creak or flex around. Just damn good headphones especially at this pricepoint!",
    image: "images/generated/gear-fiio-jadeaudio-jt7-open-back-planar-headphones-13b1ed7b.png",
    url: "https://apos.audio/products/fiio-jadeaudio-jt7-open-back-planar-headphones",
    buttonLabel: "Go and See",
    slug: "gear-fiio-jadeaudio-jt7-open-back-planar-headphones",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-fiio-jadeaudio-jt7-open-back-planar-headphones",
    detailLabel: "More from me"
  },
  {
    title: "Snowsky Echo Mini",
    category: "Gear",
    description: "Remember actually listening to your music rather than just hearing it? Well with this distraction free little player you can do just that. The sound quality is actually incredible. Grab one cheaply from your choice of dubious online retailer. I used Aliexpress.",
    image: "images/generated/gear-snowsky-echo-mini-33403ba5.jpeg",
    url: "https://www.fiio.com/echomini",
    buttonLabel: "Go and See",
    slug: "gear-snowsky-echo-mini",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-snowsky-echo-mini",
    detailLabel: "More from me"
  },
  {
    title: "GK Kunten In Ear Monitors",
    category: "Gear",
    description: "These things punch waaayyyy above their weight. Squeezing out every bit of bang for your buck the GK Kunten is fantastic complimentary IEM for the Snowsky Echo Mini. I usually have AirPod pro 2s in but it was astonishing to see how much sound quality I had traded out for convenience. They sound SO much better than my AirPods.",
    image: "images/generated/gear-gk-kunten-in-ear-monitors-d5bb9377.png",
    url: "https://www.head-fi.org/showcase/gk-kunten.28787/",
    buttonLabel: "Go and see",
    slug: "gear-gk-kunten-in-ear-monitors",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-gk-kunten-in-ear-monitors",
    detailLabel: "More from me"
  },
  {
    title: "Xteink X4",
    category: "Gear",
    description: "Don't read as much as you would like to? Well, this little thing can help. Small enough to vanish in your pocket with none of the distractions or battery life woes you have with you phone. What a cheap and cheerful little on the go device. Whip it out whenever you're waiting and enjoy your time rather than being numbed out or made angry by whatever slop the algorithms are trying to serve you today. Bonus points for installing KoReader and syncing your reading across multiple devices. I've got my comfy at home Kobo and my out and about Xteink X4.",
    image: "images/generated/gear-xteink-x4-66baed0d.jpg",
    url: "https://www.xteink.com/products/xteink-x4?variant=46914764144881",
    buttonLabel: "Go and See",
    slug: "gear-xteink-x4",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-xteink-x4",
    detailLabel: "More from me"
  },
  {
    title: "Milwaukee Fastback",
    category: "Gear",
    description: "Pocket knives get all the love in the EDC world, but they’re pricey and people treat them like fragile little pets. One bad cut into something gritty and suddenly you’ve shaved dollars off a blade you just bought. Fastback hears ya, Fastback doesn’t care. This thing is built to wade through whatever shit and piss your day throws at it. Drop it, slam it, scrape it, jam it into something you definitely shouldn’t. Doesn’t matter. Swap the blade for a fresh one from the stash in the handle and keep going. One-hand open, instant blade changes... It’s the tool you can absolutely flog without a single pang of guilt. Double sided Phillips and flat bit included.",
    image: "images/generated/gear-milwaukee-fastback-9a346e46.jpg",
    url: "https://www.milwaukeetool.com.au/hand-tools/cutting-tools/knives/48221505.html",
    buttonLabel: "Go and See",
    slug: "gear-milwaukee-fastback",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-milwaukee-fastback",
    detailLabel: "More from me"
  },
  {
    title: "Victorinox Fibrox Knives",
    category: "Gear",
    description: "Five hundred dollar Japanese steel knives still go dull. Steel is steel. Physics is physics. And marketing is marketing. Fibrox knives skip the fairy tales and get straight to being actually good. Cheap enough that you won't mind banging it through bones but so sharp that you'd better not forget you're also made of meat. The handles are where the magic is. They're grippy, comfy, non porous and seamless so easy to clean! They're designed for hands that are actually doing work rather than posing beside some artisanal bullshit for social media. It’s pure bang-for-buck function. No mythology, no ego, just a knife that does the job every single day.",
    image: "images/generated/gear-victorinox-fibrox-knives-489b8ecf.png",
    url: "https://www.victorinox.com/en/Products/Cutlery/Chef's-Knives/Fibrox-Chef%E2%80%99s-Knife/p/5.2003.31B",
    buttonLabel: "Go and See",
    slug: "gear-victorinox-fibrox-knives",
    imageAspect: "landscape",
    imageFit: "contain",
    detailUrl: "post.html?slug=gear-victorinox-fibrox-knives",
    detailLabel: "More from me"
  }
];
